const flights = [
    {
        Depart: {
            flightLogo: 'https://1000logos.net/wp-content/uploads/2020/04/Cathay-Pacific-logo.jpg',
            Depart: 'London Heathrow (LHR)',
            DepartCodename:'LHR',
            DepartTime: '11:15',
            Class: 'Economy',
            FlightNo: 252,
            Plane: 'Boeing 777',
            Transit: 'Hong Kong Intl (HKG)',
            TransitArrival: '07:35',
            TransitCodename:'HKG',
            TransitFlight: 'Hong Kong Intl (HKG)',
            TransitFlightTime: '09:00',
            TransitFlightNo: 386,
            TransitPlane: 'Airbus A330',
            Arrival: 'Beijing Intl (PEK)',
            ArrivalTime: '12:30',
            title: 'Cathay Pacific',
            ArrivalCodename:'PEK',
            Price:500,
        },
        Return: {
            flightLogo: 'https://1000logos.net/wp-content/uploads/2020/04/Cathay-Pacific-logo.jpg',
            Plane: 'Aribus A330',
            Depart: 'Bejing Capital (PEK)',
            DepartCodename:'PEK',
            DepartTime: '13:45',
            Class: 'Economy',
            FlightNo: 391,
            Plane: 'Airbus A330',
            Transit: 'Hong Kong Intl',
            TransitArrival: '18:25',
            TransitFlight: 'Hong Kong Intl (HKG)',
            TransitCodename:'HKG',
            TransitFlightTime: '22:15',
            Arrival: 'London Heathrow (LHR)',
            ArrivalTime: '05:00',
            title: 'Cathay Pacific',
            TransitFlightNo: 251,
            TransitPlane:'Boeing',
            ArrivalCodename:'LHR',
            Price:500
        }
    },
    {
        Depart: {
            flightLogo: 'https://www.cathaypacific.com/content/dam/cx/designs/responsive/images/Social-Sharing/share-facebook-ENG.originalimage.jpg',
            Depart: 'London Heathrow (LHR)',
            DepartCodename:'LHR',
            DepartTime: '11:15',
            Class: 'Business',
            FlightNo: 252,
            Plane: 'Boeing 781',
            Transit: 'Hong Kong Intl (HKG)',
            TransitArrival: '07:35',
            TransitCodename:'HKG',
            TransitFlight: 'Hong Kong Intl (HKG)',
            TransitFlightTime: '09:00',
            TransitFlightNo: 386,
            TransitPlane: 'Boeing 777',
            Arrival: 'Beijing Intl (PEK)',
            ArrivalTime: '12:30',
            title: 'Cathay Pacific',
            ArrivalCodename:'PEK',
            Price:650,
        },
        Return: {
            flightLogo: 'https://www.cathaypacific.com/content/dam/cx/designs/responsive/images/Social-Sharing/share-facebook-ENG.originalimage.jpg',
            Plane: 'Aribus A330',
            Depart: 'Bejing Intl (PEK)',
            DepartCodename:'PEK',
            DepartTime: '13:45',
            Class: 'Business',
            FlightNo: 391,
            Plane: 'Airbus A330',
            Transit: 'Hong Kong Intl',
            TransitArrival: '18:25',
            TransitFlight: 'Hong Kong Intl (HKG)',
            TransitCodename:'HKG',
            TransitFlightTime: '22:15',
            Arrival: 'London Heathrow (LHR)',
            ArrivalTime: '05:00',
            title: 'Air Asia',
            TransitFlightNo: 251,
            TransitPlane:'Boeing',
            ArrivalCodename:'LHR',
            Price:650
        }
    },
    {
        Depart: {
            flightLogo: 'https://logos-world.net/wp-content/uploads/2020/03/Qatar-Airways-Logo.png',
            Depart: 'London Heathrow (LHR)',
            DepartCodename:'LHR',
            DepartTime: '14:55',
            Class: 'Business',
            FlightNo: 9711,
            Plane: 'Boeing 781',
            Transit: 'Doha Intl (DOH)',
            TransitArrival: '00.:45',
            TransitCodename:'DOH',
            TransitFlight: 'Doha Intl (DOH)',
            TransitFlightTime: '02:20',
            TransitFlightNo: 818,
            TransitPlane: 'Boeing 777',
            Arrival: 'Hong Kong (HKG)',
            ArrivalTime: '14:45',
            title: 'Qatar Airways',
            ArrivalCodename:'HKG',
            Price:650,
        },
        Return: {
            flightLogo: 'https://logos-world.net/wp-content/uploads/2020/03/Qatar-Airways-Logo.png',
            Plane: 'Boeing 777',
            Depart: 'Hong Kong Intl (HKG)',
            DepartCodename:'HKG',
            DepartTime: '19:10',
            Class: 'Business',
            FlightNo: 817,
            Transit: 'Doha Intl (DOH)',
            TransitArrival: '23:35',
            TransitFlight: 'Doha Intl (DOH)',
            TransitCodename:'DOH',
            TransitFlightTime: '01:50',
            Arrival: 'London Heathrow (LHR)',
            ArrivalTime: '06:25',
            title: 'Qatar Airways',
            TransitFlightNo: 11,
            TransitPlane:'Airbus A380',
            ArrivalCodename:'LHR',
            Price:650
        }
    },
    {
        Depart: {
            flightLogo: 'https://1000logos.net/wp-content/uploads/2017/06/United-Airlines-logo.jpg',
            Depart: 'London Heathrow (LHR)',
            DepartCodename:'LHR',
            DepartTime: '6:50',
            Class: 'Economy',
            FlightNo: 9900,
            Plane: 'Airbus A320',
            Transit: 'Brussels National',
            TransitArrival: '08:55',
            TransitCodename:'BRU',
            TransitFlight: 'Brussels National',
            TransitFlightTime: '10:35',
            TransitFlightNo: 9929,
            TransitPlane: 'Airbus A330',
            Arrival: 'New York JF Kennedy Intl Airport (JFK)',
            ArrivalTime: '13:20',
            title: 'United',
            ArrivalCodename:'JFK',
            Price:500
        },
        Return: {
            flightLogo: 'https://1000logos.net/wp-content/uploads/2017/06/United-Airlines-logo.jpg',
            Depart: 'New York KF Kennedy Intl Aiport (JFK)',
            DepartCodename:'JFK',
            DepartTime: '18:25',
            Class: 'Economy',
            FlightNo: 9928,
            Plane: 'Airbus A330',
            Transit: 'Hong Kong Intl',
            TransitArrival: '07:40',
            TransitFlight: 'Brussels National',
            TransitCodename:'BRU',
            TransitFlightTime: '09:40',
            Arrival: 'London Heathrow',
            ArrivalTime: '10:05',
            title: 'United',
            TransitFlightNo: 9986,
            TransitPlane: 'Airbus A320',
            ArrivalCodename:'LHR',
            Price:500
        }
    }

]

module.exports = flights